config/routes.rb
Rails.application.routes.draw do
  root to: 'pictures#top'

  resources :pictures do
    collection do
      post :confirm
    end
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :users do
    resources :favorite_pictures, only: [:index]
  end

  resources :favorites, only: [:create, :destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  validates :image, :comment, presence: true
  validates :comment, length: { maximum: 140 }
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  mount_uploader :image, ImageUploader
  validates :image, \
    file_size: { \
      in: 5.kilobyte..250.kilobyte,
        message: 'ファイルのサイズは %{min} 以上 %{max} 以下にしてください' }
      # message: 'must be within %{min} and %{max}' }
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: :false }
  before_save { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :pictures
  has_many :favorites, -> { order(:id) }, dependent: :destroy
  has_many :favorite_pictures, through: :favorites, source: :picture
  mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/favorite_pictures_controller.rb
class FavoritePicturesController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @favorite_pictures = @user.favorite_pictures
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(picture_id: params[:id])
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(picture_id: params[:id]).destroy
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:new, :edit, :show, :destroy]

  def top
    render 'top'
  end

  def index
    @pictures = Picture.order(:updated_at)
  end

  def new
    if params[:back]
      @picture = Picture.new(picture_params)
      unless params[:cache][:image].empty?
        @picture.image.retrieve_from_cache! params[:cache][:image]
      end
    else
      @picture = Picture.new
      @picture.user_id = current_user.id
    end
  end

  def confirm
    @picture = Picture.new(picture_params)
    render 'new' if @picture.invalid?
  end

  def create
    @picture = Picture.new(picture_params)
    unless params[:cache][:image].empty?
      @picture.image.retrieve_from_cache! params[:cache][:image]
    end
    if @picture.save
      NotifyMailer.notify_mail(current_user).deliver
      redirect_to pictures_path, notice: "ブログを作成しました！"
    else
      render 'new'
    end
  end

  def show
    @favorite = current_user.favorites.find_by(picture_id: @picture.id)
  end

  def edit
  end

  def update
    if @picture.update(picture_params)
      redirect_to pictures_path, notice: "ブログを編集しました！"
    else
      render 'edit'
    end
  end

  def destroy
    @picture.destroy
    redirect_to pictures_path, notice: "ブログを削除しました！"
  end

  private
  def picture_params
    params.require(:picture).permit(:user_id, :comment, :image, :image_cache)
  end

  def set_picture
    @picture = Picture.find(params[:id])
  end

  def logged_in_user
    redirect_to new_session_path unless logged_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    # 画像保存（create）の際に、キャッシュから画像を復元してnewに入れる
    unless params[:cache][:avatar].empty?
      @user.avatar.retrieve_from_cache! params[:cache][:avatar]
    end
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(\
      :name, :email, :password, :password_confirmation, :avatar, :avatar_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorite_pictures/index.html.erb
<section class="bg-light" id="portfolio">
  <div class="container">

    <div class="row">
      <div class="col-lg-12 text-center">
        <h5 class="section-heading text-uppercase"><%= @user.name %>のお気に入り一覧</h5>
        <h6 class="notice"><%= notice %></h6>
      </div>
    </div>

    <div class="row">
<!-- loop for Portfolio -->
<% @favorite_pictures.each do |picture| %>
      <div class="col-md-4 col-sm-6 portfolio-item">

        <a class="portfolio-link" href="<%= picture_path(picture.id) %>">
          <div class="portfolio-hover">
            <div class="portfolio-hover-content">
              <i class="fa fa-plus fa-3x"></i>
            </div>
          </div>
          <%= image_tag(picture.image.thumb.url, class: "img-fluid idx-w") %>
        </a>

        <div class="portfolio-caption">
          <p><%= picture.comment %></p>
          <ul class="list-inline">
            <li>更新日: <%= picture.updated_at %></li>
            <li>投稿者: <%= picture.user.name %></li>
            <li>
              <% if !picture.user.avatar.thumb.file.nil? \
                 &&  picture.user.avatar.thumb.file.exists? %>
              <%= image_tag(picture.user.avatar.thumb.url) %>
              <% else %>
              <%= image_tag("/assets/no_image.png") %>
              <% end %>
            </li>
          </ul>
          <div>
            <ul class="navbar-nav">
              <li class="nav-item">
                <%= link_to "お気に入り解除する", favorite_path(id: picture.id), \
                    method: :delete, class: 'btn-danger nav-link' %>
              </li>
            </ul>
          </div>
        </div>

      </div>
<% end %>
<!-- loop for Portfolio -->
    </div>

  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>Ph3app</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="" style="">

  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav" style="">
    <div class="container">

      <%= link_to "Ph3app", '/', class: 'navbar-brand' %>

      <!-- button class="navbar-toggler navbar-toggler-right collapsed" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation" style="" -->

      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fa fa-bars"></i>
      </button>

      <!-- div class="navbar-collapse collapse" id="navbarResponsive" style="" -->
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav text-uppercase ml-auto">
<% if logged_in? %>
          <li class="nav-item">
            <%= link_to "プロフィール", user_path(current_user.id), class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", session_path(current_user.id), class: 'nav-link', method: :delete %>
          </li>
<% else %>
          <li class="nav-item">
            <%= link_to "ログイン", new_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "登録", new_user_path, class: 'nav-link' %>
          </li>
<% end %>
          <li class="nav-item">
            <%= link_to "一覧表示", pictures_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "投稿", new_picture_path, class: 'nav-link' %>
          </li>
        </ul>
      </div>

      <div class="mn-012"></div>

    </div>
  </nav>

<%= yield %>

  <footer>
    <div class="container">
      <div class="row">
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
          <span class="copyright">&copy; Dive into Code test application</span>
        </div>
        <div class="col-md-4">
        </div>
      </div>
    </div>
  </footer>

</body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: @picture, local: true, url: choose_new_or_edit) do |form| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <p></p>
      <h6><%= @picture.errors.count %>件のエラーがあります。</h6>
      <ul class="list-inline">
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :user_id %>

  <p></p>
  <h6>本文</h6>
  <%= form.text_field :comment %>

  <p></p>
  <h6>画像</h6>
  <!-- 確認画面から新規作成画面に戻った時に、 -->
  <!-- アップロードした画像を表示させるための記述 -->
  <% if !@picture.image.file.nil? && @picture.image.file.exists? %>
  <img class="img-fluid d-block mx-auto" src="/<%= @picture.image.cache_path %>" />
  <% end %>
<!--
  <#%= image_tag(@picture.image.url, class: "img-fluid d-block mx-auto") %>
 -->
  <%= form.file_field :image, id: :picture_image %>
  <!-- 確認画面から新規作成画面に戻った時に情報を保持するための記述 -->
  <%= form.hidden_field :image_cache %>

  <p></p>
  <%= form.submit '投稿', data: {dismiss: 'modal'}, class: 'btn btn-primary' %>
<% end %>

app/views/pictures/confirm.html.erb
<div class="portfolio-modal modal fade show" role="dialog" style="display: block; position: static;">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto">
            <div class="modal-body">
<h5>以下の内容で投稿</h5>

<%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
  <%= form.hidden_field :comment %>
  <%= form.hidden_field :user_id %>
  <%= hidden_field_tag :"cache[image]", @picture.image.cache_name %>

  <p></p>
  <h6>本文</h6>
  <p><%= @picture.comment %></p>

  <p></p>
  <h6>画像</h6>
  <!-- 確認画面でアップロードした画像を表示させるための記述 -->
  <img class="img-fluid d-block mx-auto" src="/<%= @picture.image.cache_path %>" />

  <%= form.submit '投稿する', data: {dismiss: 'modal'}, class: 'btn btn-primary commit-btn' %>
<% end %>

<%= form_with(model: @picture, url: new_picture_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :comment %>
  <%= form.hidden_field :user_id %>
  <%= hidden_field_tag :"cache[image]", @picture.image.cache_name %>
  <%= form.submit "もどる", name: 'back', class: 'btn back-btn' %>
<% end %>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/pictures/edit.html.erb
<div class="portfolio-modal modal fade show" role="dialog" style="display: block; position: static;">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto">
            <div class="modal-body">
<h5 class="text-uppercase">ブログ編集</h5>
<%= render 'form' %>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/pictures/index.html.erb
<section class="bg-light" id="portfolio">
  <div class="container">

    <div class="row">
      <div class="col-lg-12 text-center">
        <h5 class="section-heading text-uppercase">投稿一覧</h5>
        <h6 class="notice"><%= notice %></h6>
      </div>
    </div>

    <div class="row">
<!-- loop for Portfolio -->
<% @pictures.each do |picture| %>
      <div class="col-md-4 col-sm-6 portfolio-item">

        <a class="portfolio-link" href="<%= picture_path(picture.id) %>">
          <div class="portfolio-hover">
            <div class="portfolio-hover-content">
              <i class="fa fa-plus fa-3x"></i>
            </div>
          </div>
          <%= image_tag(picture.image.thumb.url, class: "img-fluid idx-w") %>
        </a>

        <div class="portfolio-caption">
          <p><%= picture.comment %></p>
          <ul class="list-inline">
            <li>更新日: <%= picture.updated_at %></li>
            <li>投稿者: <%= picture.user.name %></li>
            <li>
              <% if !picture.user.avatar.thumb.file.nil? \
                 &&  picture.user.avatar.thumb.file.exists? %>
              <%= image_tag(picture.user.avatar.thumb.url) %>
              <% else %>
              <%= image_tag("/assets/no_image.png") %>
              <% end %>
            </li>
          </ul>
          <div>
            <ul class="navbar-nav">
              <li class="nav-item">
                <%= link_to '確認', picture_path(picture.id), class: 'btn-default nav-link' %>
              </li>
            <% if logged_in? && picture.user_id == current_user.id %>
              <li class="nav-item">
                <%= link_to '編集', edit_picture_path(picture.id), class: 'btn-info nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to '削除', picture_path(picture.id), method: :delete, \
                    data: {confirm: '削除しますか？'}, class: 'btn-danger nav-link' %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>

      </div>
<% end %>
<!-- loop for Portfolio -->
    </div>

  </div>
</section>

app/views/pictures/new.html.erb
<div class="portfolio-modal modal fade show" role="dialog" style="display: block; position: static;">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto">
            <div class="modal-body">
<h5 class="text-uppercase">ブログ作成</h5>
<%= render 'form' %>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/pictures/show.html.erb
<div class="portfolio-modal modal fade show" role="dialog" style="display: block; position: static;">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto">
            <div class="modal-body">

              <p class="item-intro text-muted"><%= @picture.comment %></p>

              <p><%= image_tag(@picture.image.url, class: "img-fluid d-block mx-auto") %></p>

              <ul class="list-inline">
                <% unless @picture.user == current_user %>
                  <% if @favorite.present? =%>
                    <li><%= link_to "お気に入り解除する", favorite_path(id: @picture.id), \
                                     method: :delete, class: 'btn-danger' %></li>
                  <% else %>
                    <li><%= link_to "お気に入りする",    favorites_path(id: @picture.id), \
                                     method: :post, class: 'btn-primary' %></li>
                  <% end %>
                <% end %>
                <li><%= link_to "投稿一覧にもどる", pictures_path %></li>
              </ul>

            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/pictures/top.html.erb
<header class="masthead">
  <div class="container">
    <div class="intro-text">
      <div class="intro-lead-in">&nbsp;</div>
      <div class="intro-heading text-uppercase">&nbsp;</div>
    </div>
  </div>
</header>

app/views/users/new.html.erb
<section class="bg-light" id="contact">
  <div class="container">

    <div class="row">
      <div class="col-lg-12">

<%= form_with(model: @user, local: true) do |f| %>
        <% if @user.errors.any? %>
          <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
              <h6><%= @user.errors.count %>件のエラーがあります。</h6>
            </div>
            <div class="col-md-2"></div>
          </div>
          <div class="row" id="error_explanation">
            <div class="col-md-2"></div>
            <div class="col-md-8">
              <ul class="list-inline">
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
            <div class="col-md-2"></div>
          </div>
        <% end %>

          <div class="row">

            <div class="col-md-2"></div>
            <div class="col-md-8">
              <div class="form-group">
                <%= f.text_field :name, required: "required", \
                    placeholder: "名前", class: 'form-control' %>
                <p class="help-block text-danger"></p>
              </div>
              <div class="form-group">
                <%= f.email_field :email, required: "required", \
                    placeholder: "メールアドレス", class: 'form-control' %>
                <p class="help-block text-danger"></p>
              </div>
              <div class="form-group">
                <%= f.password_field :password, required: "required", \
                    placeholder: "パスワード", class: 'form-control' %>
                <p class="help-block text-danger"></p>
              </div>
              <div class="form-group">
                <%= f.password_field :password_confirmation, required: "required", \
                    placeholder: "パスワード（再入力）", class: 'form-control' %>
                <p class="help-block text-danger"></p>
              </div>
              <div class="form-group">
                <h6>アイコン画像</h6>
                <%= f.file_field :avatar, id: :user_avatar, class: 'form-control' %>
              </div>
              <!-- 確認画面から新規作成画面に戻った時         -->
              <!-- アップロードした画像を表示させるための記述 -->
              <div class="team-member">
                <% if !@user.avatar.file.nil? && @user.avatar.file.exists? %>
                <%= image_tag(@user.avatar.url, class: "mx-auto rounded-circle", alt: "アイコン画像" ) %>
                <% end %>
              </div>
              <!-- 確認画面から新規作成画面に戻った時に情報を保持するための記述 -->
              <%= f.hidden_field :avatar_cache %>
              <%= hidden_field_tag :"cache[avatar]", @user.avatar.cache_name %>
            </div>
            <div class="col-md-2"></div>

            <div class="clearfix"></div>

            <div class="col-lg-12 text-center">
              <%= f.submit "アカウント作成", class: 'btn btn-primary btn-xl' %>
            </div>

          </div>
<% end %>

      </div>
    </div>

  </div>
</section>

app/views/users/show.html.erb
<section class="bg-light" id="team">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <!-- h5 class="section-heading text-uppercase">Our Amazing Team</h5 -->
        <!-- h6 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h6 -->
      </div>
    </div>

    <div class="row">
      <div class="col-sm-4"></div>

      <div class="col-sm-4">
        <div class="team-member">
<% if !@user.avatar.file.nil? && @user.avatar.file.exists? %>
<%= image_tag(@user.avatar.url, class: "mx-auto rounded-circle", alt: "アイコン画像") %>
<% else %>
<%= image_tag("/assets/no_image.png", class: "mx-auto rounded-circle", alt: "アイコン画像") %>
<% end %>
          <h5><%= @user.name %></h5>
          <p class="text-muted">メールアドレス: <%= @user.email %></p>
          <ul class="list-inline">
            <li class="list-inline-item">
<%= link_to "お気に入りのpictureの一覧", \
    user_favorite_pictures_path(user_id: @user.id), \
    class: 'btn-default' %>
            </li>
          </ul>
        </div>
      </div>

      <div class="col-sm-4"></div>
    </div>

    <div class="row">
      <div class="col-lg-8 mx-auto text-center">
        <!-- p class="large text-muted">Lorem ipsum deaque, corporis ea, alias ut unde.</p -->
      </div>
    </div>
  </div>
</section>